// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZYgqhgi1VSuJjJWWDVnLjj_DZfpjWg2E',
    appId: '1:97897445104:web:367b035a1b1c8f13527435',
    messagingSenderId: '97897445104',
    projectId: 'hack1-app-7be85',
    authDomain: 'hack1-app-7be85.firebaseapp.com',
    storageBucket: 'hack1-app-7be85.firebasestorage.app',
    measurementId: 'G-N7LQKM02Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdDojmhdhcINaCzFT39J4V2gQ6I143rM0',
    appId: '1:97897445104:android:5271e7d751804989527435',
    messagingSenderId: '97897445104',
    projectId: 'hack1-app-7be85',
    storageBucket: 'hack1-app-7be85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE38wXjI4Hc2HeLWR3h6mOtE-eI_1Z1jQ',
    appId: '1:97897445104:ios:f5c49feb7a0d45c9527435',
    messagingSenderId: '97897445104',
    projectId: 'hack1-app-7be85',
    storageBucket: 'hack1-app-7be85.firebasestorage.app',
    iosBundleId: 'com.example.hack1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE38wXjI4Hc2HeLWR3h6mOtE-eI_1Z1jQ',
    appId: '1:97897445104:ios:f5c49feb7a0d45c9527435',
    messagingSenderId: '97897445104',
    projectId: 'hack1-app-7be85',
    storageBucket: 'hack1-app-7be85.firebasestorage.app',
    iosBundleId: 'com.example.hack1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZYgqhgi1VSuJjJWWDVnLjj_DZfpjWg2E',
    appId: '1:97897445104:web:023b575e427a1311527435',
    messagingSenderId: '97897445104',
    projectId: 'hack1-app-7be85',
    authDomain: 'hack1-app-7be85.firebaseapp.com',
    storageBucket: 'hack1-app-7be85.firebasestorage.app',
    measurementId: 'G-1RWEVTYW53',
  );
}
